services:
    horrible.command.worker:
        class: Horrible\GearmanBundle\Command\WorkerCommand
        arguments:
            - '@horrible.gearman.worker'
        tags:
            - { name: 'console.command' }