language: php
php:
  - hhvm
  - 5.6
  - 7.0

install:
  - composer install --prefer-source

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs --standard=psr2 --extensions=php --ignore=$TRAVIS_BUILD_DIR/vendor/ $TRAVIS_BUILD_DIR/
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit $TRAVIS_BUILD_DIR/

matrix:
  allow_failures:
    - php: hhvm